// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using course_std.Data;

namespace course_std.Migrations.Credits
{
    [DbContext(typeof(CreditsContext))]
    [Migration("20210528023003_CreateCredits")]
    partial class CreateCredits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("course_std.Models.Credits", b =>
                {
                    b.Property<string>("Academic")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectiveCredits")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneralCredits")
                        .HasColumnType("TEXT");

                    b.Property<string>("GraduationCredits")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredCredits")
                        .HasColumnType("TEXT");

                    b.Property<string>("Schoolsys")
                        .HasColumnType("TEXT");

                    b.ToTable("Credits");
                });
#pragma warning restore 612, 618
        }
    }
}
